import { ExternalLink } from '../components/SiteLink';
import { Link } from '../router/Router';
import { INDEPENDENT_STATUS_URL } from '../status/status';

export default function AboutPage() {
  return <>
    <header className="border-b border-white/10 bg-[radial-gradient(circle_at_top,rgba(34,211,238,.14),transparent_48%)]"><div className="mx-auto w-full max-w-5xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-200">Community and operation</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">About CK Conflux</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-300">CK Conflux is an independently and community-operated Matrix homeserver and community. It is not operated by Element or the Matrix.org Foundation.</p></div></header>
    <div className="mx-auto w-full max-w-5xl px-4 py-10 sm:px-6 lg:px-8 lg:py-14">
      <div className="grid gap-5 md:grid-cols-2">
        <section className="rounded-2xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold text-white">Who does what?</h2><div className="mt-4 space-y-4 leading-7 text-slate-300"><p><strong className="text-slate-100">CK Conflux</strong> operates its own homeserver and makes its local policy, moderation, and operational decisions.</p><p><strong className="text-slate-100">Element</strong> is the recommended app for using CK Conflux, but Element does not operate CK Conflux.</p><p><strong className="text-slate-100">Matrix</strong> is the protocol and federated network. The Matrix.org Foundation does not operate CK Conflux.</p></div></section>
        <section className="rounded-2xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold text-white">Federation has boundaries</h2><p className="mt-4 leading-7 text-slate-300">CK Conflux controls its own homeserver. It does not control third-party homeservers reached through Matrix federation; those servers have their own operators, policies, moderation, and availability.</p><Link to="/matrix" className="mt-5 inline-flex font-semibold text-cyan-200 underline">Learn how Matrix federation works</Link></section>
      </div>
      <section className="mt-5 rounded-2xl border border-cyan-300/20 bg-cyan-400/5 p-6" aria-labelledby="availability-heading"><h2 id="availability-heading" className="text-xl font-semibold text-white">Community-run availability</h2><p className="mt-3 max-w-3xl leading-7 text-slate-300">Service availability is best-effort and community-run; CK Conflux does not promise an SLA. Use the CK Conflux status route and the separately hosted independent status page as the sources for current availability.</p><div className="mt-5 flex flex-wrap gap-3"><Link to="/status" className="rounded-xl bg-cyan-400 px-4 py-2.5 font-semibold text-slate-950">View status</Link><ExternalLink href={INDEPENDENT_STATUS_URL} className="rounded-xl border border-white/15 px-4 py-2.5 font-semibold text-white hover:bg-white/10">Independent status page</ExternalLink></div></section>
      <section className="mt-5 rounded-2xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold text-white">Questions and service notices</h2><p className="mt-3 max-w-3xl leading-7 text-slate-300">Route general questions through Support. Important service notices may also be communicated through verified CK Conflux mechanisms, such as Server Notices or official rooms. Treat messages from unrelated accounts or rooms with caution.</p><Link to="/support" className="mt-5 inline-flex rounded-xl border border-white/15 px-4 py-2.5 font-semibold text-white hover:bg-white/10">Open Support</Link></section>
    </div>
  </>;
}
