import { Link } from '../router/Router';

export default function CallsPage() {
  return <>
    <section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(168,85,247,0.2),transparent_45%),radial-gradient(circle_at_25%_25%,rgba(34,211,238,0.16),transparent_30%)]" /><div className="relative mx-auto w-full max-w-6xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20">
      <p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-200">Primary voice &amp; video</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold tracking-tight text-white sm:text-5xl">Element Call</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Move naturally from a Matrix room into voice, video, and screen sharing—with the same Matrix identity you already use for chat.</p><div className="mt-7 flex flex-wrap gap-3"><a href="https://element.ckconflux.com" className="rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950">Open Element</a><Link to="/matrix" className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 font-semibold text-white">Learn about Matrix</Link></div>
    </div></section>
    <section className="mx-auto w-full max-w-6xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-200">A simple path</p><h2 className="mt-2 text-2xl font-semibold text-white sm:text-3xl">Matrix room → Element Call → voice, video, screen sharing</h2></div><div className="mt-8 grid gap-4 md:grid-cols-3">{[['1','Start in a room','Open the DM or group room where your conversation already happens.'],['2','Open Element Call','Launch the room call without creating a separate commercial conferencing account.'],['3','Talk and share','Use one-to-one or group voice and video, and share your screen on supported platforms.']].map(([number,title,copy]) => <article key={number} className="rounded-2xl border border-white/10 bg-white/5 p-5"><span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-cyan-400/15 font-semibold text-cyan-200">{number}</span><h3 className="mt-4 text-lg font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{copy}</p></article>)}</div></section>
    <section className="border-y border-white/10 bg-white/[0.025]"><div className="mx-auto grid w-full max-w-6xl gap-8 px-4 py-12 sm:px-6 lg:grid-cols-2 lg:px-8 lg:py-16"><div><h2 className="text-2xl font-semibold text-white">MatrixRTC underneath</h2><p className="mt-3 leading-7 text-slate-300">Element Call is the user-facing calling experience. MatrixRTC is the underlying Matrix real-time communications technology that connects calls with Matrix rooms and membership.</p><p className="mt-3 leading-7 text-slate-300">That integration means your room and shared Matrix identity stay at the center instead of adding another meeting login.</p></div><div className="rounded-2xl border border-cyan-300/20 bg-cyan-400/10 p-6"><h2 className="text-2xl font-semibold text-white">Community communication</h2><p className="mt-3 leading-7 text-slate-300">CK Conflux does not place advertising in Element Call. Availability and features can vary by client, browser, device, room, and configuration.</p><p className="mt-3 text-sm leading-6 text-slate-300">For exact privacy, encryption, and operational boundaries, use our security guidance rather than assuming every call has identical protections.</p><Link to="/security" className="mt-4 inline-flex rounded-xl border border-white/20 bg-white/5 px-4 py-2 font-semibold text-white">Read Security</Link></div></div></section>
    <section className="mx-auto w-full max-w-6xl px-4 py-12 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-5 rounded-2xl border border-white/10 bg-white/5 p-6 sm:flex-row sm:items-center"><div><h2 className="text-xl font-semibold text-white">Looking for assistance?</h2><p className="mt-2 text-sm text-slate-300">Find supported-platform tips and account guidance in the help center.</p></div><Link to="/help" className="rounded-xl border border-white/15 px-4 py-2 text-center font-semibold text-white">Get help</Link></div></section>
  </>;
}
