import StatusSummary from '../components/StatusSummary';
import { Link } from '../router/Router';
import { usePrefersReducedMotion } from '../hooks/usePrefersReducedMotion';

const differentiators = [
  ['Private by design', 'End-to-end encryption protects private Matrix conversations where supported.'],
  ['Federated and open', 'Matrix connects communities across an open, decentralized communication network.'],
  ['People, not profiles', 'No CK Conflux advertising, sale of personal data, or AI training on private conversations.'],
  ['Community supported', 'Core communication stays free, supported by voluntary membership.'],
];
export default function Home() {
  usePrefersReducedMotion();
  return <>
    <section className="border-b border-white/10 bg-[radial-gradient(circle_at_top,rgba(34,211,238,0.18),transparent_45%)]"><div className="mx-auto max-w-6xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-200">Element · Matrix · MatrixRTC</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold tracking-tight text-white sm:text-5xl">Private community chat, secure messaging, and calls without platform lock-in.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">CK Conflux is a community-run Matrix home for conversations in Element, with integrated voice and video through Element Call.</p><div className="mt-7 flex flex-wrap gap-3"><a href="https://element.ckconflux.com" className="rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950">Open Element</a><a href="https://element.ckconflux.com/#/register" className="rounded-xl border border-white/20 bg-white/5 px-5 py-3 font-semibold text-white">Create Account</a></div></div></section>
    <section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 lg:px-8"><h2 className="text-2xl font-semibold text-white">Communication on your terms</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{differentiators.map(([title, copy]) => <article key={title} className="rounded-2xl border border-white/10 bg-white/5 p-5"><h3 className="font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{copy}</p></article>)}</div></section>
    <section className="mx-auto grid max-w-6xl gap-4 px-4 py-8 sm:px-6 md:grid-cols-2 lg:px-8"><article className="rounded-2xl border border-cyan-300/20 bg-cyan-400/5 p-6"><p className="text-xs font-semibold uppercase tracking-widest text-cyan-200">Messaging</p><h2 className="mt-2 text-2xl font-semibold text-white">Element on Matrix</h2><p className="mt-3 leading-7 text-slate-300">Use the familiar Element app for encrypted rooms on a federated messaging network.</p><Link to="/matrix" className="mt-4 inline-flex font-semibold text-cyan-200">Explore Matrix and Element →</Link></article><article className="rounded-2xl border border-cyan-300/20 bg-cyan-400/5 p-6"><p className="text-xs font-semibold uppercase tracking-widest text-cyan-200">Voice and video</p><h2 className="mt-2 text-2xl font-semibold text-white">Element Call + MatrixRTC</h2><p className="mt-3 leading-7 text-slate-300">Start voice, video, and screen sharing from your Matrix rooms.</p><Link to="/calls" className="mt-4 inline-flex font-semibold text-cyan-200">Explore Element Call →</Link></article></section>
    <section className="mx-auto grid max-w-6xl gap-6 px-4 py-12 sm:px-6 md:grid-cols-2 lg:px-8"><div><p className="text-sm font-semibold uppercase tracking-widest text-cyan-200">Free and community funded</p><h2 className="mt-2 text-2xl font-semibold text-white">Core communication stays free</h2><p className="mt-3 leading-7 text-slate-300">Voluntary membership helps sustain infrastructure without turning private communication into a product.</p><Link to="/membership" className="mt-4 inline-flex font-semibold text-cyan-200">Membership and funding →</Link></div><StatusSummary /></section>
  </>;
}
