import { PUBLIC_CONTACTS, SUPPORTER_URL } from '../config/community';
import { Coffee, UserRound } from 'lucide-react';
import { ExternalLink } from '../components/SiteLink';
import { Link } from '../router/Router';

const REGISTER_URL = 'https://element.ckconflux.com/#/register';
const steps = [
  ['Have your details ready', <>Registration will ask for your token, an available username, an email address, and an account password. Review the <Link className="font-semibold text-cyan-200 underline" to="/terms">Terms</Link> and <Link className="font-semibold text-cyan-200 underline" to="/rules">Server Rules</Link> before continuing.</>],
  ['Register in Element', <>Use the button below to continue to Element. Element and the Matrix Authentication Service (MAS)—not this public guide—handle the actual registration and account credentials.</>],
  ['Verify your email', <>Open the verification message and follow its link. The required email confirms that you control the address used for the account and makes the enabled password-recovery path possible. Check spam or junk folders if it does not arrive.</>],
];

export default function JoinPage() {
  return <>
    <section className="border-b border-white/10 bg-[radial-gradient(circle_at_top,rgba(34,211,238,0.18),transparent_48%)]"><div className="mx-auto w-full max-w-5xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16">
      <p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-200">Join CK Conflux</p><h1 className="mt-3 max-w-3xl text-3xl font-semibold tracking-tight text-white sm:text-5xl">Create your CK Conflux Matrix account</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">A guided path from invitation to a secure account. Read these steps first, then complete registration in Element.</p>
      <div className="mt-7 flex flex-col gap-3 sm:flex-row"><a href={REGISTER_URL} className="rounded-xl bg-cyan-400 px-5 py-3 text-center font-semibold text-slate-950">Continue to Element registration</a><a href="https://element.ckconflux.com" className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 text-center font-semibold text-white">Open Element</a></div>
    </div></section>
    <section className="mx-auto w-full max-w-5xl px-4 py-12 sm:px-6 lg:px-8"><div className="grid gap-6 lg:grid-cols-[1fr_2fr]">
      <aside className="rounded-2xl border border-cyan-300/20 bg-cyan-400/[0.07] p-5 lg:sticky lg:top-24 lg:self-start" aria-labelledby="eligibility-heading"><h2 id="eligibility-heading" className="text-xl font-semibold text-white">Who can join?</h2><p className="mt-3 text-sm leading-6 text-slate-300">CK Conflux is an invitation-based community for people aged 18 or older who agree to its Terms and Server Rules. You need a valid registration token from one of the supported paths.</p><h3 className="mt-5 font-semibold text-white">Why require a token?</h3><p className="mt-2 text-sm leading-6 text-slate-300">Tokens keep registration connected to the community and help limit automated signups, spam, and abuse. A token permits registration; it does not exempt an account from community rules.</p></aside>
      <div><h2 className="text-2xl font-semibold text-white">Registration, step by step</h2><ol className="mt-5 space-y-4">
        <li className="rounded-2xl border border-cyan-300/30 bg-cyan-400/[0.06] p-5">
          <div className="flex gap-4"><span aria-hidden="true" className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-cyan-400 font-semibold text-slate-950">1</span><div><h3 className="font-semibold text-white">Get a registration token</h3><p className="mt-2 text-sm leading-6 text-slate-300">Choose either supported path below. Both provide the registration code needed to create an account.</p></div></div>
          <div className="mt-5 grid gap-4 sm:grid-cols-2">
            <article className="rounded-2xl border border-white/15 bg-slate-950/40 p-5"><UserRound aria-hidden="true" className="h-6 w-6 text-cyan-200" /><h4 className="mt-3 font-semibold text-white">Already know a member?</h4><p className="mt-2 text-sm leading-6 text-slate-300">An existing CK Conflux member can share a registration code with you. Ask them to send it privately—registration codes should never be posted publicly.</p></article>
            <article className="rounded-2xl border border-amber-300/30 bg-gradient-to-br from-amber-300/10 to-slate-950/40 p-5 shadow-lg shadow-amber-500/5"><Coffee aria-hidden="true" className="h-6 w-6 text-amber-200" /><h4 className="mt-3 font-semibold text-white">Want to support the community?</h4><p className="mt-2 text-sm leading-6 text-slate-300">Voluntary support helps operate CK Conflux and is another supported path to receive a registration code.</p><ExternalLink href={SUPPORTER_URL} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl border border-amber-200/40 bg-amber-300/15 px-4 py-2 font-semibold text-amber-50 transition motion-safe:hover:-translate-y-0.5 hover:bg-amber-300/20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-200"><Coffee aria-hidden="true" className="h-5 w-5" />Buy Me a Coffee</ExternalLink></article>
          </div>
          <p className="mt-5 rounded-xl border border-white/10 bg-slate-950/40 p-4 text-sm leading-6 text-slate-200"><strong className="text-white">Payment is not required to join CK Conflux.</strong> A valid registration code is required regardless of how you receive one. Support is always voluntary.</p>
        </li>
        {steps.map(([title, copy], index) => <li key={title} className="flex gap-4 rounded-2xl border border-white/10 bg-white/5 p-5"><span aria-hidden="true" className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-cyan-400 font-semibold text-slate-950">{index + 2}</span><div><h3 className="font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{copy}</p></div></li>)}</ol></div>
    </div></section>
    <section className="border-y border-white/10 bg-white/[0.025]"><div className="mx-auto grid w-full max-w-5xl gap-5 px-4 py-12 sm:px-6 md:grid-cols-2 lg:px-8">
      <article className="rounded-2xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold text-white">What your identity means</h2><p className="mt-3 leading-7 text-slate-300">Your permanent Matrix ID will look like <code className="rounded bg-slate-900 px-2 py-1 text-cyan-200">@name:ckconflux.com</code>. It says that CK Conflux is your homeserver and identifies you in local and compatible federated Matrix rooms. It is distinct from your changeable display name.</p></article>
      <article className="rounded-2xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-semibold text-white">Password ≠ recovery key</h2><p className="mt-3 leading-7 text-slate-300">Your account password signs you in and can be reset through the verified-email recovery flow. Your Matrix recovery key unlocks the secure backup of your end-to-end encryption keys. A password reset does not recover that encrypted history, and CK Conflux cannot recreate a lost recovery key.</p></article>
    </div></section>
    <section className="mx-auto w-full max-w-5xl px-4 py-12 sm:px-6 lg:px-8"><div className="grid gap-5 md:grid-cols-2">
      <article className="rounded-2xl border border-cyan-300/25 bg-cyan-400/10 p-6"><h2 className="text-xl font-semibold text-white">Immediately after registration</h2><p className="mt-3 text-sm leading-6 text-slate-300">Open Element, identify the rooms that appeared, understand Server Notices, and secure encryption recovery.</p><Link to="/help" className="mt-4 inline-flex rounded-xl bg-cyan-400 px-4 py-2 font-semibold text-slate-950">Continue with your first five minutes</Link><span className="mx-2 text-slate-500" aria-hidden="true">·</span><Link to="/security" className="font-semibold text-cyan-200 underline">Security &amp; recovery guidance</Link></article>
      <article className="rounded-2xl border border-amber-300/20 bg-amber-300/[0.06] p-6"><h2 className="text-xl font-semibold text-white">Registration did not work?</h2><p className="mt-3 text-sm leading-6 text-slate-300">For an invalid or rejected token, registration error, or missing verification email, contact account support. Include the step that failed and the exact error, but never send your password or recovery key.</p><a href={PUBLIC_CONTACTS.support.mailto} className="mt-4 inline-flex font-semibold text-cyan-200 underline">Email account support</a><span className="mx-2 text-slate-500" aria-hidden="true">·</span><Link to="/support" className="font-semibold text-cyan-200 underline">All support routes</Link></article>
    </div></section>
  </>;
}
