import LegalLayout from '../layout/LegalLayout';
import { Link } from '../router/Router';

export default function PrivacyPage() {
  return <LegalLayout title="CK Conflux Privacy Model" lastUpdated="August 26, 2026">
    <p>This page explains privacy across CK Conflux community services. Matrix, Mastodon, TeamSpeak, and membership/account services do not process identical data; the service-specific boundaries below apply instead of a single blanket promise. Third-party and federated services remain governed by their own operators.</p>

    <section className="rounded-2xl border border-cyan-300/25 bg-cyan-400/10 p-5"><h2 className="text-xl font-semibold text-white">Our commitments</h2><ul className="mt-3 list-disc space-y-2 pl-5"><li>CK Conflux does not sell user personal information.</li><li>CK Conflux does not use users&apos; private conversations or content to train AI models.</li><li>CK Conflux does not display advertising on its community services.</li></ul></section>

    <section><h2 className="text-xl font-semibold text-white">Information the services may process</h2><div className="mt-3 space-y-4">
      <div><h3 className="text-lg font-semibold text-white">Accounts and contact details</h3><p>Matrix account information includes your Matrix ID (MXID), account and profile settings, display name, and room relationships. A recovery or contact email may be processed where you provide one. Membership/account services may process account, support, membership, and transaction-related records needed to provide those services; payment or funding providers also apply their own policies.</p></div>
      <div><h3 className="text-lg font-semibold text-white">Authentication, access, and security data</h3><p>CK Conflux services may process login/session information, IP addresses, user-agent or client information, timestamps, and operational logs to authenticate access, troubleshoot, maintain performance, and prevent abuse. This metadata exists even when message content is end-to-end encrypted.</p></div>
      <div><h3 className="text-lg font-semibold text-white">Matrix rooms, federation, and content</h3><p>Matrix needs account identifiers, room membership and routing events, timestamps, and related room metadata to deliver and federate activity. Public or unencrypted room content may be visible to CK Conflux, room participants, and participating servers as applicable. In encrypted rooms, the server may store message and media ciphertext while participating clients hold the keys; CK Conflux cannot necessarily inspect that content in plaintext.</p></div>
    </div></section>

    <section><h2 className="text-xl font-semibold text-white">Service-specific differences</h2><ul className="mt-3 space-y-3">
      <li><strong className="text-white">Matrix:</strong> An MXID and federation data can travel to participating homeservers. Content and metadata have different visibility, and room encryption status matters. Other homeservers can retain federated data under their own policies.</li>
      <li><strong className="text-white">Mastodon:</strong> Profile fields, public posts, follows, and interactions can be public and federated. Followers-only posts and direct mentions restrict the intended audience but should not be treated as end-to-end encrypted; remote servers and recipients may store them.</li>
      <li><strong className="text-white">TeamSpeak:</strong> This optional service has a separate identity and voice workflow from Matrix. Connection, identity, channel, and operational data may be processed to run and secure it; Matrix room encryption and recovery do not apply to TeamSpeak.</li>
      <li><strong className="text-white">Membership and My Account:</strong> These services may process the account, membership, capacity, support, and provider records needed to administer benefits and voluntary support.</li>
    </ul></section>

    <section><h2 className="text-xl font-semibold text-white">Retention and deletion</h2><p>Retention is scoped by service and data type, and storage is not guaranteed indefinitely. CK Conflux Terms state that operational logs, including IP addresses, are retained for 30 days. Mastodon has separate application records: server request logs containing IP addresses may be retained for up to 90 days, and the latest login IP associated with a registered Mastodon account may be stored for up to 12 months. Account content can remain while an account or room is active, and deletion or moderation actions do not guarantee removal of copies already delivered to recipients, backups, or federated servers outside CK Conflux’s control.</p><p className="mt-2">You may request access or deletion using the contact route below. Data retention and removal remain best-effort where the Terms, technical operation, federation, legal obligations, or another user’s records require otherwise.</p></section>

    <section><h2 className="text-xl font-semibold text-white">How information is used and shared</h2><p>CK Conflux uses data to provide accounts and communications, deliver federation, administer membership, secure and troubleshoot services, prevent abuse, moderate reported content, respond to support requests, and meet legal obligations. Information may be delivered to room participants and federated servers as the user directs, handled by service providers needed to operate the service, or disclosed when legally required or necessary to protect users and services.</p><p className="mt-2">Cookies or local storage may keep sessions and preferences. Disabling them may prevent parts of a service from working. Apps you authorize and clients you install may receive data according to the access you grant and their own policies.</p></section>

    <section><h2 className="text-xl font-semibold text-white">Your choices and contact</h2><p>Review room visibility and encryption before posting, limit optional profile information, secure your account, and use available access, correction, export, or deletion controls. For privacy and data requests, email <a className="font-semibold text-cyan-200 underline" href="mailto:admin@colonelkrud.com">admin@colonelkrud.com</a>. Abuse reports may use built-in reporting or <a className="font-semibold text-cyan-200 underline" href="mailto:abuse@mg.colonelkrud.com">abuse@mg.colonelkrud.com</a>.</p><p className="mt-2">For encryption and recovery boundaries, read <Link className="font-semibold text-cyan-200 underline" to="/security">Security</Link>. Account eligibility and legal obligations remain in the <Link className="font-semibold text-cyan-200 underline" to="/terms">Terms</Link>.</p></section>
  </LegalLayout>;
}
