import { ACCOUNT_PORTAL_URL, ELEMENT_IDENTITY_RESET_GUIDE_URL, PASSWORD_RECOVERY_URL, PUBLIC_CONTACTS } from '../config/community';
import { Link } from '../router/Router';

const linkClass = 'font-semibold text-cyan-200 underline';
const routes = [
  ['Learning Element', 'Start with Matrix IDs, rooms, DMs, Spaces, notifications, calls, and everyday controls.', <Link className={linkClass} to="/help">Open Help</Link>],
  ['Forgot account password', 'First use Element’s Forgot password flow with the verified email on your account. If self-service recovery fails, include your MXID and exact error when contacting support—never send a password or recovery key.', <><a className={linkClass} href={PASSWORD_RECOVERY_URL}>Reset password in Element</a><span> · </span><a className={linkClass} href={PUBLIC_CONTACTS.support.mailto}>Email account support</a></>],
  ['Verification email problem', 'Confirm the address is correct, check spam or junk, wait a few minutes, and request one fresh message. If the newest link still fails, send account support your MXID, attempt time, and exact error.', <a className={linkClass} href={PUBLIC_CONTACTS.support.mailto}>Email account support</a>],
  ['Can sign in but old encrypted messages are unavailable', 'Signing in or resetting a password does not restore encryption keys. Verify this session from a trusted device or restore secure backup with your recovery key.', <Link className={linkClass} to="/security">Security and recovery-key guidance</Link>],
  ['No recovery key and no verified device', 'Use Element’s digital-identity reset guidance. A password reset does not recreate encryption keys, and CK Conflux operators do not possess keys that could decrypt or restore your old encrypted messages.', <><a className={linkClass} href={ELEMENT_IDENTITY_RESET_GUIDE_URL}>Element identity recovery/reset guidance</a><span> · </span><a className={linkClass} href={PUBLIC_CONTACTS.security.mailto}>Email security</a></>],
  ['Harassment or abuse', 'Use report, ignore, or block in your client. Include useful context when reporting; encrypted content may require you to submit the relevant evidence.', <><Link className={linkClass} to="/help">Reporting steps</Link><span> · </span><a className={linkClass} href={PUBLIC_CONTACTS.abuse.mailto}>Email abuse</a></>],
  ['Privacy or data request', 'Request access or deletion through the published privacy contact and review service-specific retention first.', <><Link className={linkClass} to="/privacy">Privacy model</Link><span> · </span><a className={linkClass} href={PUBLIC_CONTACTS.privacy.mailto}>Privacy contact</a></>],
  ['Service outage', 'Check current availability and incident information independently of this site.', <><Link className={linkClass} to="/status">Status route</Link><span> · </span><a className={linkClass} href="https://status.ckconflux.com">Independent status page</a></>],
  ['Membership or storage', 'Review membership and capacity information, then manage available account options in My Account.', <><Link className={linkClass} to="/membership">Membership</Link><span> · </span><a className={linkClass} href={ACCOUNT_PORTAL_URL}>My Account</a></>],
];

export default function SupportPage() {
  return <section className="mx-auto w-full max-w-5xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-200">Find the right path</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Support</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-300">Choose what you need help with. These routes separate learning, account recovery, moderation, privacy, availability, and membership so your request reaches an existing destination.</p><div className="mt-8 grid gap-4 md:grid-cols-2">{routes.map(([title, copy, action]) => <article key={title} className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="text-xl font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{copy}</p><div className="mt-4 text-sm">{action}</div></article>)}</div></section>;
}
