import { Link } from '../router/Router';

const routes = [
  ['Learning Element', 'Start with Matrix IDs, rooms, DMs, Spaces, notifications, calls, and everyday controls.', <Link className="font-semibold text-cyan-200 underline" to="/help">Open Help</Link>],
  ['Sign-in or account failure', 'For registration, sign-in, verification-email, or account access failures, use the existing account support contact.', <a className="font-semibold text-cyan-200 underline" href="mailto:admin@colonelkrud.com">Email account support</a>],
  ['Lost encrypted history or recovery', 'A successful login does not restore encryption keys. Follow recovery guidance before resetting anything; CK Conflux cannot recreate a lost recovery key.', <Link className="font-semibold text-cyan-200 underline" to="/security">Recovery guidance</Link>],
  ['Harassment or abuse', 'Use report, ignore, or block in your client. Include useful context when reporting; encrypted content may require you to submit the relevant evidence.', <><Link className="font-semibold text-cyan-200 underline" to="/help">Reporting steps</Link><span> · </span><a className="font-semibold text-cyan-200 underline" href="mailto:abuse@mg.colonelkrud.com">Email abuse</a></>],
  ['Privacy or data request', 'Request access or deletion through the published privacy contact and review service-specific retention first.', <><Link className="font-semibold text-cyan-200 underline" to="/privacy">Privacy model</Link><span> · </span><a className="font-semibold text-cyan-200 underline" href="mailto:admin@colonelkrud.com">Privacy contact</a></>],
  ['Service outage', 'Check current availability and incident information independently of this site.', <><Link className="font-semibold text-cyan-200 underline" to="/status">Status route</Link><span> · </span><a className="font-semibold text-cyan-200 underline" href="https://status.ckconflux.com">Independent status page</a></>],
  ['Membership or storage', 'Review membership and capacity information, then manage available account options in My Account.', <><Link className="font-semibold text-cyan-200 underline" to="/membership">Membership</Link><span> · </span><a className="font-semibold text-cyan-200 underline" href="https://account.ckconflux.com">My Account</a></>],
];

export default function SupportPage() {
  return <section className="mx-auto w-full max-w-5xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-cyan-200">Find the right path</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Support</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-300">Choose what you need help with. These routes separate learning, account recovery, moderation, privacy, availability, and membership so your request reaches an existing destination.</p><div className="mt-8 grid gap-4 md:grid-cols-2">{routes.map(([title, copy, action]) => <article key={title} className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="text-xl font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-300">{copy}</p><div className="mt-4 text-sm">{action}</div></article>)}</div></section>;
}
