import { Link } from '../router/Router';

export default function TeamSpeakPage() {
  return <section className="mx-auto w-full max-w-5xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16">
    <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Optional secondary voice service</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white sm:text-4xl">TeamSpeak 6 Beta</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-300">TeamSpeak 6 Beta is available as an optional, separate voice workflow. For the preferred CK Conflux experience integrated with Matrix rooms and your Matrix identity, use Element Call.</p>
    <div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-6"><p className="text-sm font-semibold uppercase tracking-widest text-slate-400">Server target</p><code className="mt-2 block text-xl font-semibold text-cyan-200">ts6.ckconflux.com</code><div className="mt-5 flex flex-wrap gap-3"><a href="ts3server://ts6.ckconflux.com" className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 font-semibold text-white">Connect to TeamSpeak</a><a href="https://www.teamspeak.com/en/downloads/" className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 font-semibold text-white">Official TeamSpeak downloads</a></div></div>
    <div className="mt-8 grid gap-4 md:grid-cols-2"><article className="rounded-2xl border border-amber-300/20 bg-amber-300/[0.06] p-5"><h2 className="text-xl font-semibold text-white">What beta means</h2><p className="mt-2 text-sm leading-6 text-slate-300">TeamSpeak 6 is beta software. Stability, features, and client compatibility may change, and some devices or workflows may not work as expected. Do not assume TeamSpeak 3 state, history, plugins, or settings automatically migrate into TeamSpeak 6.</p></article><article className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><h2 className="text-xl font-semibold text-white">A separate identity and workflow</h2><p className="mt-2 text-sm leading-6 text-slate-300">TeamSpeak 6 identity and setup are separate from Matrix and Element. It does not share your Matrix rooms, Matrix ID, or Element onboarding.</p></article></div>
    <div className="mt-10 rounded-2xl border border-cyan-300/25 bg-cyan-400/10 p-6"><p className="text-xs font-semibold uppercase tracking-widest text-cyan-200">Recommended first</p><h2 className="mt-2 text-2xl font-semibold text-white">Use Element Call for integrated calling</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Keep chat, room membership, voice, video, and screen sharing together in the primary CK Conflux experience.</p><Link to="/calls" className="mt-4 inline-flex rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950">Explore Element Call</Link></div>
    <div className="mt-6 flex gap-5 text-sm"><Link to="/security" className="font-semibold text-cyan-200 underline">Security</Link><Link to="/help" className="font-semibold text-cyan-200 underline">Help</Link></div>
  </section>;
}
